config/routes.rb
ZeldaBase::Application.routes.draw do
  resources :items

  resources :games

  resources :temples

  resources :votes

  resources :users

  root :to => "pages#home"

  get '/signin' => 'sessions#new', :as => 'sign_in'

  post '/sessions/create' => 'sessions#create'
  
  delete '/signout' => 'sessions#destroy', :as => 'sign_out'

  

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :temples
	has_many :items
	has_many :votes

	validates :name, :uniqueness => true
	validates :name, :trailer_url, :released, :station, :presence => true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :trailer_url, :description, :emulator_url, :rom_url, :released, :station)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
    <%= form_for(@game) do |f| %>
      <% if @game.errors.any? %>
        <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-5">
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :trailer_url %><br />
        <%= f.text_field :trailer_url %>
      </div>
      <div class="field">
        <%= f.label :emulator_url %><br />
        <%= f.text_field :emulator_url %>
      </div>
      <div class="field">
        <%= f.label :rom_url %><br />
        <%= f.text_field :rom_url %>
      </div>

      <div class="field">
        <%= f.label :year_released %><br />
        <%= f.number_field :released %>
      </div>
      <div class="field">
        <%= f.label :station %><br />
        <%= f.text_field :station %>
      </div>
    </div>
      <div class="col-lg-5">
        <div class="field">
          <%= f.label :description %><br />
          <%= f.text_area :description %>
        </div>
      </div> 
  </div>
  <div class="actions">
    <%= f.submit %>
    <% end %>
  </div>

app/views/games/edit.html.erb
<div class= "container">
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>
</div>

app/views/games/index.html.erb
<div class= "container">
<div class="jumbotron">
  <div class="row">
  <div class="col-lg-8">
    <h1>Games</h1>
    <% if session[:user_id] != nil %>
    <%= link_to 'New Game', new_game_path, class:"btn btn-success btn-lg"%>
    <% end %>
  </div>
  <div class="col-lg-2">
    <%= image_tag("ZeldaLogo.jpg", :size => "281x209") %>
  </div>
</div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Year Released</th>
      <th>Station</th>
      <th></th>
    </tr>
  </thead>

<% @games.each do |game| %>
  <tr>
    <td><%= game.name %></td>
    <td><%= game.released %></td>
    <td><%= game.station %></td>
    <td>
        <div class="btn-group">
            <%= link_to 'Show', game, class:"btn btn-primary" %>
            <% if session[:user_id] != nil %>
            <%= link_to 'Edit', edit_game_path(game), class:"btn btn-warning" %>
              <% if User.find_by_id(session[:user_id]).username == "administrator" %>
              <%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
              <% end %>
            <% end %>
            
        </div>
    </td>        
  </tr>
<% end %>
</table>

<br />
</div>

app/views/games/new.html.erb
<div class= "container">
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>
</div>

app/views/games/show.html.erb
<div class= "container">
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1><%= @game.name %></h1>
  <div align="center">
  <p>
    <iframe width="560" height="315" src="//www.youtube.com/embed/<%= @game.trailer_url.split("=")[1] %>" frameborder="0" allowfullscreen align:center></iframe>
  </p>
  <div class="btn-group">
    <% if(@game.emulator_url!=""||@game.rom_url!="") %>
      <a href= <%=@game.emulator_url %> class="btn btn-default btn-lg">Emulator URL</a>
      <a href= <%= @game.rom_url %> class="btn btn-default btn-lg">Rom URL</a>
    <% else%>
      <p>Emulator or Rom not yet Available</p>
    <%end%>
  </div>
</div>
</div>
  <% if @game.description=="" %>
  <p><strong>No Description Available</strong></p>
  <% else %>
  <p>
    <strong>Description:</strong>  
    <% @game.description.split("\n").each do |paragraph| %>
    <br>
    &nbsp; &nbsp; &nbsp; &nbsp; <%= paragraph %>
    </br>
    <% end %>
  </p>
  <% end %>
<div class="row">
<div class="col-lg-5">
  <p>
    <strong>Temples</strong>
  <ul>
  <% @game.temples.each do |temple| %>
      <li>
      <%= link_to temple.name, temple_url(temple.id)  %>
      </li>
  <% end %>
</ul>
</p>
</div>
<div class="col-lg-5">
    <p>
    <strong>Items</strong>
  <ul>
  <% @game.temples.each do |temple| %>
    <% temple.items.each do |item| %>
      <li>
      <%= link_to item.name, item_url(item.id)  %>
      </li>
    <%end%>
  <% end %>
</ul>
</p>
</ul>
</p>
</div>
</div>
  <p><strong>Votes:</strong>
      <ul>
      <% @game.votes.each do |vote| %>
        <li><%=vote.user.username%></li>
      <%end%>
    </ul>
  </p>
<div class="btn-group">
  <a href= <%= edit_game_path(@game) %> class="btn btn-warning btn-lg">Edit</a>
  <a href="/games" class="btn btn-primary btn-lg">Back</a>
</div>
</div>