config/routes.rb
ZeldaBase::Application.routes.draw do
  resources :items

  resources :games

  resources :temples

  resources :votes

  resources :users

  root :to => "pages#home"

  get '/signin' => 'sessions#new', :as => 'sign_in'

  post '/sessions/create' => 'sessions#create'
  
  delete '/signout' => 'sessions#destroy', :as => 'sign_out'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zelda Base</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	 <div class="navbar navbar-inverse">
        <div class="container">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Zelda Base", root_url, :class => 'navbar-brand'  %>
          <div class="nav-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Games", games_url  %></li>
              <li><%= link_to "Dungeons", temples_url  %></li>
              <li><%= link_to "Items", items_url  %></li>
              <li><%= link_to "Users", users_url  %></li>
              <li><%= link_to "Votes", votes_url  %></li>
            </ul>
            <% u = User.find_by_id(session[:user_id]) %>
            <% if session[:user_id] %>
              <ul class="nav navbar-nav pull-right">
                <li><%= link_to "Sign Out", sign_out_url, method: 'delete' %></li>
              </ul>
              <p class="navbar-text pull-right">Signed in as <a href="/users/<%= session[:user_id] %>" class="navbar-link"><%= u.username %></a></p>
            <% else %>
              <ul class="nav navbar-nav pull-right">
                <li><%= link_to "Sign In", sign_in_url  %></li>
                <li><%= link_to "Sign Up", new_user_url  %></li>
              </ul>
            <% end %>
           </div><!-- /.nav-collapse -->
        </div><!-- /.container -->
     </div><!-- /.navbar -->
<%= yield %>

</body>
</html>