config/routes.rb
ZeldaBase::Application.routes.draw do
  resources :items

  resources :games

  resources :temples

  resources :votes

  resources :users

  root :to => "pages#home"

  get '/signin' => 'sessions#new', :as => 'sign_in'

  post '/sessions/create' => 'sessions#create'
  
  delete '/signout' => 'sessions#destroy', :as => 'sign_out'

  

end

app/models/temple.rb
class Temple < ActiveRecord::Base
	belongs_to :game
	has_many :items

	validates :name, :uniqueness => true
	validates :name, :picture_url, :description, :half_boss, :boss, :order, :game_id, :presence => true
end

app/controllers/temples_controller.rb
class TemplesController < ApplicationController
  before_action :set_temple, only: [:show, :edit, :update, :destroy]

  # GET /temples
  # GET /temples.json
  def index
    @temples = Temple.all
  end

  # GET /temples/1
  # GET /temples/1.json
  def show
  end

  # GET /temples/new
  def new
    @temple = Temple.new
  end

  # GET /temples/1/edit
  def edit
  end

  # POST /temples
  # POST /temples.json
  def create
    @temple = Temple.new(temple_params)

    respond_to do |format|
      if @temple.save
        format.html { redirect_to @temple, notice: 'Temple was successfully created.' }
        format.json { render action: 'show', status: :created, location: @temple }
      else
        format.html { render action: 'new' }
        format.json { render json: @temple.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temples/1
  # PATCH/PUT /temples/1.json
  def update
    respond_to do |format|
      if @temple.update(temple_params)
        format.html { redirect_to @temple, notice: 'Temple was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @temple.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temples/1
  # DELETE /temples/1.json
  def destroy
    @temple.destroy
    respond_to do |format|
      format.html { redirect_to temples_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temple
      @temple = Temple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temple_params
      params.require(:temple).permit(:name, :picture_url, :description, :mini_boss, :boss, :order, :game_id, :integer)
    end
end

app/helpers/temples_helper.rb
module TemplesHelper
end

app/views/temples/_form.html.erb
<%= form_for(@temple) do |f| %>
  <% if @temple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temple.errors.count, "error") %> prohibited this temple from being saved:</h2>

      <ul>
      <% @temple.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-lg-5">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture_url %><br>
    <%= f.text_field :picture_url %>
  </div>
  <div class="field">
    <%= f.label :mini_boss %><br>
    <%= f.text_field :mini_boss %>
  </div>
  <div class="field">
    <%= f.label :boss %><br>
    <%= f.text_field :boss %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.select(:game_id, options_from_collection_for_select(Game.all, :id, :name)) %>
  </div>
</div>
<div class="col-lg-5">
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
</div>
</div>
  <div class="actions">
    <%= f.submit %>
    <% end %>
  </div>

app/views/temples/edit.html.erb
<div class= "container">
<h1>Editing Temple</h1>

<%= render 'form' %>

<%= link_to 'Show', @temple %> |
<%= link_to 'Back', temples_path %>
</div>

app/views/temples/index.html.erb
<div class= "container">
<div class="jumbotron">
  <div class="row">
  <div class="col-lg-8">
    <h1>Dungeons</h1>
    <%= link_to 'New Temple', new_temple_path, class:"btn btn-success btn-lg"%>
  </div>
  <div class="col-lg-2">
    <%= image_tag("ZeldaLogo.jpg", :size => "281x209") %>
  </div>
</div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Game</th>
      <th>Order</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @temples.each do |temple| %>
      <tr>
        <td><%= temple.name %></td>
        <td><%= temple.game.name %></td>
        <td><% if temple.order==1 %>
        1st
      <% elsif temple.order==2 %>
        2nd
      <% elsif temple.order==3 %>
        3rd
      <% else %>
        <%=temple.order%>th
      <% end %></td>
        <td>
          <div class="btn-group">
          <%= link_to 'Show', temple, class:"btn btn-primary" %>
          <%= link_to 'Edit', edit_temple_path(temple), class:"btn btn-warning" %>
          <%= link_to 'Destroy', temple, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
        </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div

app/views/temples/new.html.erb
<div class= "container">
<h1>New Temple</h1>

<%= render 'form' %>

<%= link_to 'Back', temples_path %>
</div>

app/views/temples/show.html.erb
<div class= "container">
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <div class="row">
  <div class="col-lg-8">
    <h1><%= @temple.name %></h1>
    <p> The <%= @temple.name %> is the 
      <% if @temple.order==1 %>
        1st
      <% elsif @temple.order==2 %>
        2nd
      <% elsif @temple.order==3 %>
        3rd
      <% else %>
        <%=@temple.order%>th
      <% end %>
      temple in <%= link_to @temple.game.name, game_url(@temple.game.id)  %>.
    </p>
  </div>
  <div class="col-lg-2">
    <img src="<%= @temple.picture_url %>" height="200" width="300"> </img>
  </div>
</div>

  <div class="row">
  <div class="col-lg-3">
    <p>
    <strong>Item:</strong>
    <% @temple.items.each do |item| %>
      <%= link_to item.name, item_url(item.id)  %>
    <%end%>
  </p>
  </div>
  <div class="col-lg-3">
    <p>
      <strong>Boss:</strong>
      <%= @temple.boss %>
    </p>
  </div>
  <div class="col-lg-3">
    <p>
    <strong>Mini boss:</strong>
    <%= @temple.mini_boss %>
    </p>
  </div>
</div>
</div>


<p>
    <strong>Description:</strong>
    <% @temple.description.split("\n").each do |paragraph| %>
    <br>
    &nbsp; &nbsp; &nbsp; &nbsp; <%= paragraph %>
    </br>
    <% end %>
  </p>

<div class="btn-group">
  <%= link_to 'Edit', edit_temple_path(@temple), class:"btn btn-warning" %>
  <%= link_to 'Back', temples_path, class:"btn btn-primary" %>
</div>
</div>